# build_lab01_reference.tcl
# Reference build of the week 4 slot 1 hardware (Vivado project "lab01") on the
# Cora Z7-07S, from an empty project all the way to a bitstream and an .xsa.
#
# This is NOT the lab. In class the students build this project by hand
# (W4_S1 7.2 - 7.5) and that is the practice. Use this script when:
#   - a student could not finish, or the project got broken, and there is no
#     time to rebuild it during class
#   - LAB02 has to go ahead anyway (it starts by copying lab01 to lab02b)
#   - the instructor wants to confirm the design still builds on 2023.2
#
# The design it builds (W4_S1, chapter 7):
#   ZYNQ7 PS with the board preset, M_AXI_GP0 enabled
#     -> AXI Interconnect (ps7_0_axi_periph) -> ONE AXI GPIO, two channels
#   axi_gpio_0  ch1 All Inputs  w2 -> btn  = BTN0, BTN1
#               ch2 All Outputs w3 -> led0 = RGB LED0 (R, G, B)
#   Expected address: axi_gpio_0 at 0x4120_0000, range 64K
#   NO interrupt here - ip2intc_irpt / IRQ_F2P arrive in week 5.
#
# PORT NAMES - the GPIO / GPIO2 *interfaces* are externalised (as in W4_S1
# 7.3.4), so Vivado appends a suffix per live member and the top-level ports
# come out as btn_tri_i[1:0] and led0_tri_o[2:0]. See W4_S1 figure 7-11.
#
# This script therefore writes its own my.xdc with those names, instead of
# using xdc/cora_z7_07s_week04_lab01.xdc - that reference file is written with
# the names btn[0..1] / led0[0..2] and would give "no ports matched" here. The
# generated file is called my.xdc on purpose: it is the same name students give
# it when they save constraints from I/O Planning in W4_S1 7.5 step 7.
#
# Pins (boards/board_summary.pdf):
#   btn_tri_i[0]  D20   BTN0        led0_tri_o[0]  N15   red
#   btn_tri_i[1]  D19   BTN1        led0_tri_o[1]  G17   green
#                                   led0_tri_o[2]  L15   blue
#
# Usage:
#   cd <the LAB01 folder that holds this file>
#   vivado -mode batch -source build_lab01_reference.tcl
#   # optional, and recommended: choose a SHORT ASCII build path first
#   #   set env(W4_BUILD_DIR) C:/vw4        (Vivado GUI Tcl console)
#   #   set W4_BUILD_DIR=C:/vw4            (Windows cmd, before launching)
#
# Output: <build dir>/lab01/ , including
#   lab01/lab01.runs/impl_1/design_1_wrapper.bit
#   lab01/design_1_wrapper.xsa     <- what Vitis needs (W4_S1 7.6)
#
# After this, LAB02 can proceed normally: open lab01 and use
# File -> Save Project As... to copy it to lab02b (W4_S2 8.1).
#
# STATUS: draft, not yet run on Vivado 2023.2.
# =========================================================================

set script_dir [file normalize [file dirname [info script]]]

# ---- where to build -----------------------------------------------------
# Vivado is unhappy with long paths and with non-ASCII characters in them.
# This repo often sits under a Korean folder name (...\문서\GitHub\...), so
# fall back to a short ASCII path automatically in that case.
set build_dir $script_dir
if {[info exists ::env(W4_BUILD_DIR)] && $::env(W4_BUILD_DIR) ne ""} {
    set build_dir [file normalize $::env(W4_BUILD_DIR)]
    puts "Build directory from W4_BUILD_DIR: $build_dir"
} elseif {![regexp {^[ -~]*$} $script_dir]} {
    set build_dir "C:/vivado_w4"
    puts "NOTE: this script's path contains non-ASCII characters:"
    puts "        $script_dir"
    puts "      Vivado can fail on such paths, so building in $build_dir instead."
    puts "      Set W4_BUILD_DIR to choose a different location."
}
file mkdir $build_dir

set proj_name "lab01"
set proj_dir  [file join $build_dir $proj_name]
if {[file exists $proj_dir]} {
    puts "Removing existing $proj_dir and recreating it."
    file delete -force $proj_dir
}

# ---- project ------------------------------------------------------------
create_project $proj_name $proj_dir -part xc7z007sclg400-1

if {[catch {set_property board_part digilentinc.com:cora-z7-07s:part0:1.1 [current_project]} err]} {
    puts "board_part 1.1 failed ($err) - looking for the newest installed version."
    set bp [lindex [get_board_parts -quiet *cora-z7-07s*] end]
    if {$bp ne ""} {
        set_property board_part $bp [current_project]
        puts "board_part set to $bp."
    } else {
        puts "ERROR: cora-z7-07s board file not found. Install it first (W1_S2 2.2)."
        puts "       The board preset is required for the PS DDR/MIO settings."
        return -code error "missing cora-z7-07s board file"
    }
}

# ---- constraints --------------------------------------------------------
# Written here rather than taken from xdc/, because of the _tri_i / _tri_o
# port names explained in the header.
file mkdir $proj_dir
set my_xdc [file join $proj_dir "my.xdc"]
set fh [open $my_xdc w]
puts $fh "## my.xdc - generated by build_lab01_reference.tcl"
puts $fh "## Same result as saving constraints from I/O Planning in W4_S1 7.5."
puts $fh {set_property -dict { PACKAGE_PIN D20  IOSTANDARD LVCMOS33 } [get_ports { btn_tri_i[0] }];}
puts $fh {set_property -dict { PACKAGE_PIN D19  IOSTANDARD LVCMOS33 } [get_ports { btn_tri_i[1] }];}
puts $fh {set_property -dict { PACKAGE_PIN N15  IOSTANDARD LVCMOS33 } [get_ports { led0_tri_o[0] }];}
puts $fh {set_property -dict { PACKAGE_PIN G17  IOSTANDARD LVCMOS33 } [get_ports { led0_tri_o[1] }];}
puts $fh {set_property -dict { PACKAGE_PIN L15  IOSTANDARD LVCMOS33 } [get_ports { led0_tri_o[2] }];}
close $fh
add_files -fileset constrs_1 -norecurse $my_xdc
puts "Wrote constraints: $my_xdc"

# ---- block design -------------------------------------------------------
create_bd_design design_1

# ZYNQ7 PS with the board preset (= Run Block Automation in the GUI, W4_S1 7.2).
set ps [create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 \
            processing_system7_0]
apply_bd_automation -rule xilinx.com:bd_rule:processing_system7 \
    -config {make_external "FIXED_IO, DDR" apply_board_preset "1" \
             Master "Disable" Slave "Disable"} $ps

# The one PS switch the students turn on by hand in W4_S1 7.2.
# Fabric interrupts stay OFF - that is week 5's change.
set_property -dict [list CONFIG.PCW_USE_M_AXI_GP0 {1}] $ps

# AXI GPIO, dual channel (W4_S1 7.3.2).
#   C_ALL_INPUTS    / C_GPIO_WIDTH  -> channel 1 = btn  (2 inputs)
#   C_ALL_OUTPUTS_2 / C_GPIO2_WIDTH -> channel 2 = led0 (3 outputs)
set gpio [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_gpio:2.0 axi_gpio_0]
set_property -dict [list \
    CONFIG.C_ALL_INPUTS {1} \
    CONFIG.C_GPIO_WIDTH {2} \
    CONFIG.C_IS_DUAL {1} \
    CONFIG.C_ALL_OUTPUTS_2 {1} \
    CONFIG.C_GPIO2_WIDTH {3} \
] $gpio

# S_AXI only (W4_S1 7.3.3) - this also creates the AXI Interconnect and the
# Processor System Reset, exactly as Run Connection Automation does.
apply_bd_automation -rule xilinx.com:bd_rule:axi4 \
    -config {Clk_master {Auto} Clk_slave {Auto} Clk_xbar {Auto} \
             Master {/processing_system7_0/M_AXI_GP0} \
             Slave {/axi_gpio_0/S_AXI} ddr_seg {Auto} \
             intc_ip {New AXI Interconnect} master_apm {0}} \
    [get_bd_intf_pins axi_gpio_0/S_AXI]

# External ports from the INTERFACES (W4_S1 7.3.4), so Vivado appends
# _tri_i / _tri_o per live member -> btn_tri_i[1:0], led0_tri_o[2:0].
make_bd_intf_pins_external -name btn  [get_bd_intf_pins axi_gpio_0/GPIO]
make_bd_intf_pins_external -name led0 [get_bd_intf_pins axi_gpio_0/GPIO2]

assign_bd_address
regenerate_bd_layout
validate_bd_design
save_bd_design

puts ""
puts "==== ADDRESSES (compare with the Address Editor, W4_S1 7.4) ===="
# Expected: one line, axi_gpio_0 at 0x4120_0000, range 64K. The C code in
# src/btn_led_reg.c hard-codes 0x41200000, so if this differs, edit
# AXI_GPIO_BASEADDR in that file to match.
set ps_space [get_bd_addr_spaces -quiet processing_system7_0/Data]
foreach seg [get_bd_addr_segs -quiet -of_objects $ps_space] {
    puts [format "  %-46s offset %s  range %s" \
              $seg [get_property -quiet OFFSET $seg] \
              [get_property -quiet RANGE $seg]]
}

# ---- wrapper ------------------------------------------------------------
make_wrapper -files [get_files design_1.bd] -top
add_files -norecurse \
    [file join $proj_dir "$proj_name.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v"]
set_property top design_1_wrapper [current_fileset]
update_compile_order -fileset sources_1

# Print the real top-level port names. If they and my.xdc disagree,
# synthesis warns "no ports matched" - this is where to look first.
puts ""
puts "==== TOP-LEVEL PORTS (must match the generated my.xdc) ===="
foreach p [lsort [get_bd_ports -quiet]] {
    puts "  BD port : $p"
}
foreach p [lsort [get_bd_intf_ports -quiet]] {
    puts "  BD intf : $p"
}

# ---- synthesis, implementation, bitstream --------------------------------
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

puts ""
puts "==== RESULT ===="
puts "impl_1 status  : [get_property STATUS   [get_runs impl_1]]"
puts "impl_1 progress: [get_property PROGRESS [get_runs impl_1]]"
puts "WNS            : [get_property STATS.WNS [get_runs impl_1]]"

if {[get_property PROGRESS [get_runs impl_1]] ne "100%"} {
    puts "ERROR: implementation did not finish - no .xsa written."
    return -code error "impl_1 incomplete"
}

# ---- export hardware, bitstream included (= Export Hardware in the GUI) --
open_run impl_1
set xsa [file join $proj_dir design_1_wrapper.xsa]
write_hw_platform -fixed -include_bit -force -file $xsa

set bit [file join $proj_dir $proj_name.runs impl_1 design_1_wrapper.bit]
puts ""
puts "bitstream : $bit"
puts "XSA       : $xsa"
puts ""
puts "Next (W4_S1 7.6): in Vitis create platform w4_platform from this .xsa,"
puts "                  build it, then Application lab01_app with"
puts "                  src/btn_led_reg.c. Check that AXI_GPIO_BASEADDR in"
puts "                  that file matches the address printed above."
puts "For LAB02 (W4_S2 8.1): open this lab01 project and use"
puts "                  File -> Save Project As... to copy it to lab02b."
